import { DISPOSAL_OPTIONS, EFFICIENCY_RATINGS } from '../models/appliance';

export default async function () {
  return [
    {
      name: 'Frigider',
      description: 'Frigider eficient energetic',
      productionYear: 2020,
      energyUsage: 250,
      CO2Emissions: 120,
      expectedLifespan: 12,
      disposalOptions: DISPOSAL_OPTIONS[0],
      efficiencyRating: EFFICIENCY_RATINGS[1],
      materialComposition: {
        metal: 70,
        plastic: 25,
        other: 5,
      },
    },
    {
      name: 'Cuptor cu microunde',
      description: 'Cuptor cu microunde compact',
      productionYear: 2021,
      energyUsage: 200,
      CO2Emissions: 90,
      expectedLifespan: 10,
      disposalOptions: DISPOSAL_OPTIONS[0],
      efficiencyRating: EFFICIENCY_RATINGS[3],
      materialComposition: {
        metal: 55,
        plastic: 40,
        other: 5,
      },
    },
    {
      name: 'Mașină de spălat',
      description: 'Mașină de spălat cu încărcare frontală',
      productionYear: 2019,
      energyUsage: 180,
      CO2Emissions: 75,
      expectedLifespan: 10,
      disposalOptions: DISPOSAL_OPTIONS[0],
      efficiencyRating: EFFICIENCY_RATINGS[2],
      materialComposition: {
        metal: 60,
        plastic: 35,
        other: 5,
      },
    },
    {
      name: 'Aspirator',
      description: 'Aspirator fără sac, eficient energetic',
      productionYear: 2018,
      energyUsage: 150,
      CO2Emissions: 65,
      expectedLifespan: 8,
      disposalOptions: DISPOSAL_OPTIONS[1],
      efficiencyRating: EFFICIENCY_RATINGS[4],
      materialComposition: {
        metal: 30,
        plastic: 60,
        other: 10,
      },
    },
    {
      name: 'Televizor',
      description: 'Televizor LED 4K Ultra HD',
      productionYear: 2022,
      energyUsage: 120,
      CO2Emissions: 50,
      expectedLifespan: 7,
      disposalOptions: DISPOSAL_OPTIONS[2],
      efficiencyRating: EFFICIENCY_RATINGS[0],
      materialComposition: {
        metal: 20,
        plastic: 70,
        other: 10,
      },
    },
    {
      name: 'Aer condiționat',
      description: 'Aer condiționat inverter',
      productionYear: 2021,
      energyUsage: 300,
      CO2Emissions: 150,
      expectedLifespan: 15,
      disposalOptions: DISPOSAL_OPTIONS[0],
      efficiencyRating: EFFICIENCY_RATINGS[1],
      materialComposition: {
        metal: 50,
        plastic: 45,
        other: 5,
      },
    },
    {
      name: 'Cuptor electric',
      description: 'Cuptor electric multifuncțional',
      productionYear: 2020,
      energyUsage: 220,
      CO2Emissions: 110,
      expectedLifespan: 12,
      disposalOptions: DISPOSAL_OPTIONS[0],
      efficiencyRating: EFFICIENCY_RATINGS[2],
      materialComposition: {
        metal: 65,
        plastic: 30,
        other: 5,
      },
    },
  ];
}
